[flavor]
# dark = "gruvbox-dark"
dark = "kanagawa"
light = "kanagawa-lotus"

# PDF codepoint from nerd font
# [[icon.exts]]
# name = "pdf"
# text = "î™½"
# fg_dark = "#b30b00"
# fg_light = "#b30b00"


